"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import MEDIA_ROOT, MEDIA_URL

# from django.conf.global_settings import STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(=d(z&huoy6vzhw!h4ko@0gjm=4e^fp&9tanm1q491hd+hak^v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "debug_toolbar",

    'goods',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

#! 1) Indi isə POSTGRESQL db-sini qoşmaq lazımdır. 
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        #! 2) SQLITE3  sözünü silərək  əvəzində  POSTGRESQL  yazırıq. 
        'ENGINE'    :   'django.db.backends.postgresql',
        #! 3) Və aşağıdakı ATRİBUTLARI əlavə edirik.  Biz POSTGRESQL sistemini komputere qurasdirdigimiz üçün artıq komputerde avtomatik olaraq bir DB mövcuddur. 
        #!    Həmin DB-sin adı 'POSTGRES' adlanır. İndi bu DB-sin adını və digər atributlarını aşağıda yazasıyıq və baxasıyıq ki, içində nələr var.  
        'NAME'      :   'postgres',
        'USER'      :   'postgres',   # 4) USER adıda eyni adlanır. 
        'PASSWORD'  :   'root',       # 5) PASSWORD biz POSTGRESQL proqramını quraşdıranda özümüz yazmışdıq.
        'HOST'      :   'localhost',  # 6) HOST default olaraq 'localhost' adlanır çox vaxt
        'PORT'      :   '5432',       # 7) PORT olaraq isə proqramı quraşdırdığımızda gördüyümüz port-dur.
    }
}
#! 8) Yuxarıdakıların hamısını etdikdən sonra komputerdə quraşdırılı olan 'PG Admin 4' adlı proqramı açırıq. Sol tərəfdə PostgreSQL 16 deyilən bir yazı olacaq ona klikləyərək parolu daxil edirik və Entere basırıq. 
#!    artıq DB-in içindəyik. Şəkil № 3-də həmin DB-si ( POSTGRES ) və TABLE sütununu görə bilərik. Adətən default olan POSTGRES db-sinə toxunmurlar və yenisini yaradırlar. 



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / 'static',
    ]




MEDIA_URL = 'media/'   
MEDIA_ROOT = BASE_DIR / 'media'




INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'