"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import MEDIA_ROOT, MEDIA_URL

# from django.conf.global_settings import STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(=d(z&huoy6vzhw!h4ko@0gjm=4e^fp&9tanm1q491hd+hak^v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "debug_toolbar",

    'goods',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / 'static',
    ]


# 1) 45ci dersde serveri işə saldıqda görürük ki, saytda şəkillər açmır. Əvvəl Şəkillərimiz      "STATIC/DEPS/IMAGES/GOODS"    qovlugunun içində idi....  URL-ni isə MANUL olaraq 
# yerləşdirmişdik DİCT içinə: 
                                # context = {
                                #     "title": "Home - Catalog",
                                #     "goods": [
                                #         {
                                #             "image": "deps/images/goods/imageNAme.jpg",
                                #              ...
                                #         },
                                #     ],
                                # }

# Şablonda isə çağırmaq üçün belə yazırdıq:  #*   <img src="      {% static product.image %}      "     >

# Indi isə artıq bir DB-imiz var və bu DB içində İMAGE adında sütun mövcuddur. Ancaq hələki bu sahə boş olduğu üçün hal-hazırda şəkillərimiz açılmır. 
# Çünki 1ci səbəb həmin İMAGE sahəsinin boş olmasıdır 2ci səbəb isə artıq şəkillərimizi MEDİA adlı qovluğa yerləşdirəcəyik. 

# Bunun üçün bir kod yazmalıyıq. Bu kod biz şəkil əlavə etdikdə şəklin özünü MEDİA qovluğuna şəklin yolunu isə İMAGE sütununa qoymalıdır. Beləliklə PRODUCT.İMAGE yazdıqda
# həmin yol bizi MEDİA qovluğundakı şəkilə götürəcək və şəkillər açılacaq. 


# 2) SETTINGS.PY faylının 127ci sətrində necə ki, STATIC_URL ilə STATİC qovluğunu işarə etmişik. Eyni cür MEDİA qovluğunuda qeydiyyata salmalıyıq. Bunun üçün MEDİA_ROOT və MEDİA_URL
# constantlarından istifadə edəcəyik. 

# 3) Burda yazdigimiz 'MEDIA/' sözü qovluğun adı deyildir. Linkin başına əlavə ediləcək PREFİKS-dir.
MEDIA_URL = 'media/'   


# 4) Şəkillər əslində serverdə yerləşdirilir. Ancaq test rejimində olduğumuz üçün MEDİA qovluğuna biz qoyasıyıq. Bu qovlugu icindeki fayllari sistemde axtarib tapmasi ucunde 
# 'MEDIA_ROOT' constantından istifadə edəcəyik. Test rejimində olduğumuz üçündə əlavə olaraq bəzi şeylərdə yazmalıyıq ki (BASE_DIR kimi), həmin qovluq və fayllar işləsin. 
MEDIA_ROOT = BASE_DIR / 'media'
# 5) Yolu təyin edərək MEDIA_ROOT constantına qoyduqdan sonra URLS.PY faylına gedirik. 



INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'